#!/usr/bin/env python3
"""
inserts a new document in a collection based on kwargs
"""


def insert_school(mongo_collection, **kwargs):
    """
    returns the new _id
    (inserted_id: attribute generated by insertOne()
    is used to access the _id of the newly inserted document)
    """
    if mongo_collection is None:
        return None
    new_id = mongo_collection.insert_one(kwargs).inserted_id
    return new_id
